### ISSUE TITLE
we need a way to select and delete all regions

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#1754] opened 2021-12-29 17:15 UTC
I have loaded in a region file.  I have created a new version and now want to delete all the region from the first load. But there is now way for me to select all regions and delete them. The region file has about 100 regions so going through each one and deleting them individually is not practical.  There should be a way for the user to select all regions and then deleted.

**Comment by veggiesaurus** [comment] 2021-12-30 11:07
Duplicate of #1040

**Closed as completed** 2021-12-30 11:08 UTC
Labels: enhancement
