### ISSUE TITLE
missing grid lines when zooming the Q vs U scatter plot in the Stokes widget

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#578] opened 2019-10-28 06:56 UTC
frontend: ee77422

when zooming in in the Q vs U scatter plot in the Stokes widget, the grid lines may disappear even when zooming out. Double click will get then back.
![Screen Shot 2019-10-28 at 14 51 15](https://user-images.githubusercontent.com/20819712/67657847-edb34100-f992-11e9-9dc0-7d21515e0cd6.png)

**Comment by panchyo0** [comment] 2019-10-28 17:06
@kswang1029 which file are you using for testing? I can't reproduce this on my computer.

**Comment by kswang1029** [comment] 2019-10-29 05:46
Please try with the attached file. 
[IRCp10216_sci.spw0.cube.IQUV.manual.pbcor.line.image.zip](https://github.com/CARTAvis/carta-frontend/files/3781883/IRCp10216_sci.spw0.cube.IQUV.manual.pbcor.line.image.zip)

**Comment by Kechil** [comment] 2019-11-16 18:48
We can't reliably reproduce this bug

**Comment by veggiesaurus** [comment] 2020-12-15 07:10
likely to be resolved by migrating to plotly

**Closed** 2021-02-20 04:07 UTC
Labels: bug
