### ISSUE TITLE
import craft region files does not support global parameters

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#547] opened 2019-10-05 11:34 UTC
I tried importing a crtf region file with global color=white and linewidth=1 and the file failed to load.  Seem like the importer does not recognise some global parameters.

**Comment by veggiesaurus** [comment] 2019-10-05 11:50
@arusstaylor neither DS9 nor CRTF importing currently support styling parameters. Is this a duplicate of https://github.com/CARTAvis/carta-backend/issues/340?

(I imagine adding support for these features would be for both inline and global parameters)

**Comment by arusstaylor** [comment] 2019-10-05 15:09
Yes it looks like this is a duplicate of bs k end issue 340.

**Closed** 2019-10-05 17:27 UTC
Labels: bug
