### ISSUE TITLE
Image name does not update when image closed

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-frontend#1701] opened 2021-11-17 01:25 UTC
If you have multiple images open, select one image then close it (File > Close Image), the tab still says the name of the closed image.

**Comment by kswang1029** [comment] 2021-11-17 01:30
related to #1686

**Comment by kswang1029** [comment] 2021-11-17 01:32
The intended behavior would be:
1) if there are other images, the tab title should be the "active" image.
2) if there is no image left, the tab title should be reset.

**Comment by veggiesaurus** [comment] 2022-03-10 13:19
@kswang1029 can we close this in favour of https://github.com/CARTAvis/carta-frontend/issues/1686?

**Comment by kswang1029** [comment] 2022-03-10 13:38
Yes

**Closed as completed** 2022-03-10 14:27 UTC
Labels: bug
