### ISSUE TITLE
reload get blank frontend layout when backend is lost

### ISSUE THREAD

**Issue by duidae** [CARTAvis/carta-frontend#833] opened 2020-03-23 05:34 UTC
![image](https://user-images.githubusercontent.com/25971696/77284911-c88ce980-6d0a-11ea-932e-fcaa292277d2.png)

the issue is due to commit c43ee944d9ed2fb564b37cdb5370a828b2113d8b

@veggiesaurus  is it ok to put it back?

**Comment by veggiesaurus** [comment] 2020-04-06 11:13
> ![image](https://user-images.githubusercontent.com/25971696/77284911-c88ce980-6d0a-11ea-932e-fcaa292277d2.png)
> 
> the issue is due to commit [c43ee94](https://github.com/CARTAvis/carta-frontend/commit/c43ee944d9ed2fb564b37cdb5370a828b2113d8b)
> 
> @veggiesaurus is it ok to put it back?

I don't think we should be initialising it twice. We should rather display an error message indicating that the connection is broken. When resuming, we should apply the layout only if it hasn't been applied already

**Comment by duidae** [comment] 2020-04-07 08:51
the original logic is: after initialization, applying the layout from preference ("db of backend" or localstorage) when connection is built. So, when obtaining the layout in preference, we still need a waiting state, and if in this waiting state we dont want to apply a layout, probably keep the splash screen?

**Comment by veggiesaurus** [comment] 2020-04-09 07:46
Yes, that sounds like a good idea. Although it may cause issues when handling authentication, but I think our improvements to authentication (using token-based, separating the auth process out of CARTA itself) should solve this

**Comment by veggiesaurus** [comment] 2020-07-01 07:02
@kswang1029 I think this is fixed now, by PR #965. Can you confirm?

**Comment by kswang1029** [comment] 2020-07-01 07:55
@veggiesaurus @duidae what's the expected behavior? Like this?
http://carta.asiaa.sinica.edu.tw/frontend/4dba14f/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socket5041
where the backend is not running due to build issue (for now).

**Comment by veggiesaurus** [comment] 2020-07-01 08:20
> @veggiesaurus @duidae what's the expected behavior? Like this?
> http://carta.asiaa.sinica.edu.tw/frontend/4dba14f/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socket5041
> where the backend is not running due to build issue (for now).

Perhaps we want to keep the splash screen? Maybe with a log message "Reconnecting to backend server"?

**Comment by kswang1029** [comment] 2020-07-01 08:25
Yes, showing some messages to inform users the status is a good idea.

**Closed as completed** 2020-07-10 09:33 UTC
Labels: bug
