### ISSUE TITLE
Opening a CASA image with a trailing / using the URL parameter doesn't work properly

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#1816] opened 2022-03-30 08:16 UTC
**Describe the bug**
@Jordatious found this issue. If you open a CASA image using the `?file=<CASA image path>/` (note trailing slash), then odd things happen:

- The current folder gets set to the _inside_ of the CASA image, rather than the containing directory
- Resuming sessions seems to break

**To Reproduce**
1. Go to a CARTA browser instance and add `?file=<CASA image path>/`
2. Open the file browser. The starting folder will be incorrect.
3. Resume the session after disconnecting. This will fail.

**Expected behavior**
Resuming should work, and the file browser should start in the containing folder, rather than the image folder.

**Comment by veggiesaurus** [comment] 2022-03-30 08:17
Perhaps we need to remove the trailing `/` on the frontend side. But we then need to be able to deduce whether the supplied path is a _folder_ or a CASA image.

**Comment by veggiesaurus** [comment] 2023-06-28 10:17
@YuHsuan-Hwang to see what happens if you just remove the trailing slash in the `file` query parameter

**Comment by confluence** [comment] 2024-01-30 10:05
[This backend issue](https://github.com/CARTAvis/carta-backend/issues/1357) is a duplicate of this. I think that this should be fixed in the backend -- the backend is incorrectly splitting the image path into its components in this edge case.

**Closed as completed** 2024-03-25 08:56 UTC
Labels: bug
