### ISSUE TITLE
Symbolic link expansion causes failures

### ISSUE THREAD

**Issue by keflavich** [CARTAvis/carta-frontend#2256] opened 2023-09-18 16:55 UTC
When data are stored in a directory that includes a symbolic link, starting in v4 (not v4beta), the symbolic link gets expanded to the full path, which is not generally correct.

**Comment by veggiesaurus** [comment] 2023-09-18 18:24
Closing as duplicate of https://github.com/CARTAvis/carta-backend/issues/1314 😄 

@kswang1029 critical bug that needs a hotfix?

**Closed as not planned** 2023-09-18 18:25 UTC
