### ISSUE TITLE
[imageviewer] no png image is saved

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#102] opened 2018-12-11 03:37 UTC
with this snapshot version taken on dec 11 (http://alma.asiaa.sinica.edu.tw/_downloads/CARTA-v1.0-beta1.dmg), sometimes (no sure how to reproduce it exactly but it does happen) the file name becomes "download" and no image is saved. In normal case, it is its image name plus time tag and image can be saved.

<img width="1144" alt="screen shot 2018-12-11 at 11 36 12" src="https://user-images.githubusercontent.com/20819712/49776921-21648880-fd39-11e8-95ef-31ed2fbb38cf.png">

**Comment by veggiesaurus** [comment] 2018-12-11 03:52
Does this happen with specific files, or is it seemingly random?

**Comment by kswang1029** [comment] 2018-12-11 04:17
it seems random. Not sure how I made it twice.

**Comment by veggiesaurus** [comment] 2018-12-11 08:55
if you manually change the name to "download.png", does it save?

**Comment by kswang1029** [comment] 2018-12-11 09:09
if it is already "download.png", no image is saved. If it is some normal name and we change it to download.png, yes, it can be saved.

**Comment by veggiesaurus** [comment] 2018-12-12 05:56
@kswang1029 can you try to reproduce this in chrome?

**Comment by kswang1029** [comment] 2018-12-12 06:04
with dev-viewer via chrome, I see an image is directly saved without asking file name, unlike the desktop version which does ask if the pre-defined file name needs to be changed or not.

**Comment by veggiesaurus** [comment] 2018-12-12 06:05
That's the intended behaviour, and will be based on how your browser is configured. But can you reproduce the actual bug (no file downloaded, or the file name changed)?

**Comment by kswang1029** [comment] 2018-12-12 06:08
No, cannot reproduce the issue with dev-viewer with chrome.

**Comment by kswang1029** [comment] 2018-12-12 06:19
I tested the same desktop version v1.0-beta2 with my iMac (10.13) and MacBook Pro (10.12) and do exactly the same steps. I see the issue happens only with my laptop. Could this an OS level issue?

**Comment by veggiesaurus** [comment] 2018-12-12 06:22
it could be, yes. I haven't been able to reproduce it on any other platform. To be clear, are these the steps you're using to reproduce?
- Load supermosaic
- Zoom to 100% (or zoom to fit)
- Save image

**Comment by kswang1029** [comment] 2018-12-12 07:01
Update: I encountered this issue with iMac (10.13) too through different trigger steps... :(

**Comment by veggiesaurus** [comment] 2018-12-12 07:20
but still only with the desktop versions? @ajm-asiaa perhaps the electron apps need to use the electron file saving functionality?

**Comment by ajm-asiaa** [comment] 2018-12-12 09:05
I'm not sure if there is special electron file saving functionality, but maybe we could rule Electron out by bypassing it completely?
You can open the frontend html in your webrowser and start the backend manually.
For example (for the CARTA-v1.0-beta2 Mac version installed in the default location) go to this URL in your web browser:
file:///Applications/CARTA-v1.0-beta2.app/Contents/Resources/app/index.html
and start up the backend:
cd /Applications/CARTA-v1.0-beta2.app/Contents/Resources/app/carta-backend/bin
./run.sh

**Comment by veggiesaurus** [comment] 2018-12-13 12:56
@ajm-asiaa how do we get access to the electron dev console?

**Comment by ajm-asiaa** [comment] 2018-12-13 13:18
You can "add mainWindow.webContents.openDevTools()" to the "main.js" file. For example, if you are using the latest Mac version, open "vi /Applications/CARTA-v1.0-beta2.app/Contents/Resources/app/main.js" and insert that line under the "new BrowserWindow" line e.g. `    if (process.platform === 'darwin') {
    mainWindow = new BrowserWindow({width: 1920, height: 1080});
    mainWindow.webContents.openDevTools()
}` or equivalent place if you are using the ubuntu version. The dev console will appear once you open the app again.

**Comment by duidae** [comment] 2019-04-16 07:22
reproduce: only happens on Mac, and when canvas.toDataURL() returns a large image from supermosaic.10.fits by using zoom to 1.0x, the download would fail

reason: the limitation of a.href in Chrome on Mac should be shorter than other platform, so large string assign to a.herf would fail, and toDataURL() is only suitable for short object

solution: replace toDataURL() in canvas with toBlob()

**Closed** 2019-04-16 09:57 UTC
Labels: bug
