### ISSUE TITLE
performance degradation when editing file name for region export

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#967] opened 2020-06-29 14:57 UTC
This happens when there are lots of (image) files in the folder where a region file is going to be created. In the region file browser, when editing the file name for region export, typing is laggy.

**Comment by veggiesaurus** [comment] 2020-07-01 20:10
I think this has the same root cause as #968

**Comment by veggiesaurus** [comment] 2020-07-06 09:18
@kswang1029 is this fixed now?

**Comment by kswang1029** [comment] 2020-07-06 09:47
yes! just checked.

**Closed as completed** 2020-07-06 10:07 UTC
Labels: bug
