### ISSUE TITLE
Error when trying to build project from scratch

### ISSUE THREAD

**Issue by Seeker93** [CARTAvis/carta-frontend#885] opened 2020-04-17 20:49 UTC
Hi everyone. 

I have been trying to build this from scratch on a Debian distribution, and things go smoothly in general. But after following the build steps and running "npm start", I am met with the following error (in the Master branch)

`(46,26): Property 'BOOL' does not exist on type 'typeof EntryType'.`

Is this a known issue or did I miss a build step somewhere?

**Comment by veggiesaurus** [comment] 2020-04-22 10:14
It looks to me like you're building the `dev` branch of `carta-frontend` with the `master` branch of `carta-protobuf`. You'll need to check out `master` for `carta-frontend`, `carta-backend` and `carta-protobuf` in order to build the correct versions. Sorry if this wasn't clear from the readme!

`master` should currently correspond to CARTA 1.3 (the branch was recently updated, so you'll need to `git pull` to get the latest.

There are unfortunately some build issues in `master` as well, relating to a dependency (`@types/chart.js`) that has been updated with some regressions. For now, I suggest you explicitly install version 2.9.12 of that package: `npm install --save @types/chart.js@2.9.12`.

**Comment by Kechil** [comment] 2020-06-24 12:24
@ajm-asiaa please check

**Comment by ajm-ska** [comment] 2020-09-03 05:44
I have tried this in a `debian:buster` Docker container with the latest carta-frontend 'dev' branch. 
It seems to work fine. I can not reproduce the error.
It was probably as @veggiesaurus noted, an incompatibility with an updated npm dependency at the time that has since been fixed.
I believe there should be no problems now, and we can close this issue.

**Closed as completed by ajm-ska** 2020-09-03 05:44 UTC
