### ISSUE TITLE
frame label and other info out of sync with image change when animating between frames

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#815] opened 2020-03-04 12:05 UTC
When I animate on frames the fame label in the tab on the image window and the cursor value display (and the frame indicate in the animation widget) changes out of sync with the image itself.  They should all be synchronised.

**Comment by kswang1029** [comment] 2020-03-04 12:23
@arusstaylor is this what you saw?

![Mar-04-2020 20-27-46](https://user-images.githubusercontent.com/20819712/75879654-b2e87a80-5e56-11ea-9a4c-c21a7e725b97.gif)

**Comment by arusstaylor** [comment] 2020-03-16 12:52
A related issue is that if the frame rate is set higher than the image animation can keep up with the rest of the information updates but the image itself does not.  The rate at which the image can be animated should determine the rate of update of the rest of the layout info.

**Comment by veggiesaurus** [comment] 2020-03-16 20:17
> A related issue is that if the frame rate is set higher than the image animation can keep up with the rest of the information updates but the image itself does not. The rate at which the image can be animated should determine the rate of update of the rest of the layout info.

I think what you're seeing is related to messed up animation flow control, which @robsimmonds needs to fix

**Comment by arusstaylor** [comment] 2020-04-15 17:15
This is still a problem and makes blinking images with the animator basically non-functional in some cases, particulalry if latency is not fast.  Is this being worked on?

**Comment by veggiesaurus** [comment] 2020-04-15 17:53
> This is still a problem and makes blinking images with the animator basically non-functional in some cases, particulalry if latency is not fast.  Is this being worked on?

Yes, I'm working on it at the moment. The issue is that currently we only have one image cached on the GPU at a time, and each time the image changes, the tiles have to be decompressed again from the CPU cache and copied to the GPU. I'm working on a feature that will allow multiple images to reside in the GPU cache

**Comment by veggiesaurus** [comment] 2020-04-16 08:00
@arusstaylor I'm not sure why latency is an issue, though. Currently, when switching between images, it decompresses tiles from the existing compressed cache, and shouldn't be sending any requests to the server.

edit: actually, I see where it comes in. It seems to still be sending the spatial profiles each time. Not sure if there's a way around that other than simply closing the spatial profile widgets

**Comment by kswang1029** [comment] 2021-07-12 02:59
@veggiesaurus do you think this can be fixed/improved via tile cache improvement?

**Comment by veggiesaurus** [comment] 2021-07-12 05:21
> @veggiesaurus do you think this can be fixed/improved via tile cache improvement?

It should be fixed, yes. At least when not animating too quickly

**Comment by veggiesaurus** [comment] 2021-07-26 11:27
@kswang1029 is this fixed now?

**Comment by kswang1029** [comment] 2022-01-05 06:11
this should have been addressed.

**Closed as completed by kswang1029** 2022-01-05 06:11 UTC
Labels: bug
