### ISSUE TITLE
stokes animation ineffective due to rendering issues

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-frontend#596] opened 2019-11-06 08:53 UTC
when I change Stokes display using the animation tool there is a significant delay when changing frames due to the rehistgraming.  For example when I start at Stokes I and then change to Stokes Q,  the Stokes Q frame still displays the Stokes I image for a short period then changes to Stokes Q then after short delay the Stokes Q image changes to a new render.  This makes running an animation along the Stokes axis or even blinking between Stokes I and Q or U basically inoperable. I suspect the problem is in the implementation of independent render limits between the Stokes frames.

**Comment by veggiesaurus** [comment] 2019-11-06 09:03
@arusstaylor Which file did you encounter this with? When _playing_ an animation, I can't reproduce this issue, but when manually changing channels, I can reproduce this issue.

**Comment by arusstaylor** [comment] 2019-11-06 09:11
The files in /carta_share/groups/mightee/lennart/show-tclean

Just tried it again.  Running play in the animation doesn't produce the effect.  But if I select another Stokes with the mouse it happens.  Start on Stokes I, then select Stokes Q with the mouse. What seems to happen is that the Stokes I image data is displayed with the new render limits before being replaced by the Stokes Q.  If run as an animation this does not happen.  (Although I am pretty sure I was getting the effect in animation mode when I tried it before).

**Comment by veggiesaurus** [comment] 2019-11-06 09:21
Right, I think I see what's going on. When playing back an animation, the histogram is delivered at the same time as the data, so it's probably not going to occur. 

When not in animation mode, the histogram is delivered first, followed by the tiles (one-by-one). As per your request a while ago, we only show the new image once all tiles have arrived. However, it seems that the `Stokes` value is being set as soon as the histogram arrives, which then changes the render config bounds. 

I think the solution is to only change the `Stokes` value once all tiles have been delivered. For now, the workaround is to use animation playback and the new "animation mode" dropdown to blink between Stokes values.

**Comment by arusstaylor** [comment] 2019-11-06 10:34
Ok thanks.  I think the user expectation is that clicking on the stokes selection in the animator produces behaviour that its equivalent to changing state by running the animator.

**Comment by arusstaylor** [comment] 2019-11-19 08:49
Note that the same behaviour occurs when I use the  "Next", "Prev", "First" and "Last" options in the animator bar to change Stokes.

**Comment by veggiesaurus** [comment] 2020-02-17 16:16
should be fixed by PR #745

**Comment by veggiesaurus** [comment] 2020-02-24 18:28
@arusstaylor can you confirm that this is fixed on carta-testing?

**Comment by arusstaylor** [comment] 2020-02-24 20:53
Much better.

**Closed** 2020-02-24 21:05 UTC
Labels: bug
